### ISSUE TITLE
store location is not accurate 

### ISSUE THREAD

**Issue by a970032** [Smile-SA/elasticsuite-for-retailer#12]
store location is not accurate because 
smile_retailer_address latitude longitude is FLOAT data type
Please change to DECIMAL(10,8) and DECIMAL(11,8)

**Comment by delyriand** [comment]
Hi @a970032 

Thank you for this report.
Indeed, type of fields `latitude` and `longitude` in `smile_retailer_address` is not correct and inserted values are truncated.

But, according to Google's documentation, we can put an precision of 6 on the 2 fields and a lenght of 10 : https://developers.google.com/maps/solutions/store-locator/clothing-store-locator?csw=1#creating-a-table-in-mysql

Do you have an example of value that would force us to put something else? Without answer from you, we will put the type FLOAT (10, 6)

Best regards,

**Comment by a970032** [comment]
In my opinion i prefer decimal data type on number which has decimal place although float data type can also store decimal place but floating point has a problem it is not storing the actual number when you need the lat lon to calculate it may cast problem 
But for storing purpose its okay thanks for the update
