### ISSUE TITLE
"RetailerId" does not have corresponding setter (Support for M2.2)

### ISSUE THREAD

**Issue by samc2810** [Smile-SA/elasticsuite-for-retailer#15]
Hi Smile Team

I saw that the Minimum version requirement for the module is 2.1.x. We just installed it on 2.2.3 and seems to work basically, but we get an exception in Checkout if you select a store
Could this be a compatibility problem? Are there any plans for M2.2 support?

### Preconditions

Magento Version : M2.2.3

ElasticSuite for Retailer Version : 1.2.0

Environment : Production

Third party modules : Elasticsuite
    'Dotdigitalgroup_Email' => 1,
    'Magento_WishlistAnalytics' => 1,
    'Mageplaza_Core' => 1,
    'Mageplaza_LayeredNavigation' => 1,
    'Nosto_Tagging' => 1,
    'Shopial_Facebook' => 1,
    'Smartwave_Core' => 1,
    'Smartwave_Filterproducts' => 1,
    'Smartwave_Megamenu' => 1,
    'Smartwave_Porto' => 1,
    'Smartwave_Socialfeeds' => 1,
    'Smile_ElasticsuiteCore' => 1,
    'Smile_ElasticsuiteCatalog' => 1,
    'Smile_ElasticsuiteCatalogRule' => 1,
    'Smile_ElasticsuiteCatalogOptimizer' => 1,
    'Smile_ElasticsuiteSwatches' => 1,
    'Smile_ElasticsuiteThesaurus' => 1,
    'Smile_ElasticsuiteTracker' => 1,
    'Smile_ElasticsuiteVirtualCategory' => 1,
    'Smile_Map' => 1,
    'Smile_Seller' => 1,
    'Smile_Retailer' => 1,
    'Smile_Offer' => 1,
    'Smile_StoreLocator' => 1,
    'Smile_StoreDelivery' => 1,
    'Smile_RetailerOffer' => 1,
    'Temando_Shipping' => 1,
    'WeltPixel_Backend' => 1,
    'WeltPixel_Quickview' => 1,

### Steps to reproduce

1. Select a store in Checkout

### Expected result

1. One should see the payment step

### Actual result

following exception
[2018-09-05 14:22:51] main.CRITICAL: Report ID: webapi-5b8fe6bbd4296; Message: Property "RetailerId" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-5b8fe6bbd4296; Message: Property \"RetailerId\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php:205, LogicException(code: 0): Property \"RetailerId\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /var/www/html/vendor/magento/framework/Reflection/NameFinder.php:100)"} []

**Comment by delyriand** [comment]
Hi @samc2810 ,

Can you try with the latest version of the module (1.4.1)?

**Comment by samc2810** [comment]
Hi @delyriand 
Thanx for the instant reply. Same error with 1.4.1
Any tips on how I could go by fixing this? Or is it already in your pipeline?

Cheers sam

**Comment by delyriand** [comment]
I have never encountered this error ...
After update version, did you remove all the caches?

**Comment by samc2810** [comment]
ofcourse :)
the first thing I learned as a MAG-Developer "always clean the cache and Reindex" :D hehe

you mean with Mag2.2? The Admin-Backend Works just fine, the store-locator too but only the delivery to store is throwing this exception. So I was guessing that it could be a compatibility problem
also I checked the extension_attributes.xml the above mentioned Interface is not used in the module. May be a reason for the error?

**Comment by delyriand** [comment]
The store-delivery module (and all retailer modules) is compatible with magento 2.2. I use magento 2.2.5 for testing and i don't have this error when I choose delivery in store, i pass well to the payment step
Is the store-delivery module in version 1.1.0? 

Normally, magento generates a `Magento\Quote\Api\Data\AddressExtensionInterface` file from the extension_attributes.xml files (look in `generated` folder). And in this class, you must have `getRetailerId` and `setRetailerId` methods. For me, this php file contain:
```php
<?php
namespace Magento\Quote\Api\Data;

/**
 * ExtensionInterface class for @see \Magento\Quote\Api\Data\AddressInterface
 */
interface AddressExtensionInterface extends \Magento\Framework\Api\ExtensionAttributesInterface
{
    /**
     * @return int|null
     */
    public function getGiftRegistryId();

    /**
     * @param int $giftRegistryId
     * @return $this
     */
    public function setGiftRegistryId($giftRegistryId);

    /**
     * @return int|null
     */
    public function getRetailerId();

    /**
     * @param int $retailerId
     * @return $this
     */
    public function setRetailerId($retailerId);

    /**
     * @return \Magento\Framework\Api\AttributeInterface[]|null
     */
    public function getCheckoutFields();

    /**
     * @param \Magento\Framework\Api\AttributeInterface[] $checkoutFields
     * @return $this
     */
    public function setCheckoutFields($checkoutFields);
}
```

**Comment by samc2810** [comment]
store-delivery
![image](https://user-images.githubusercontent.com/1092318/45223774-7dda8680-b2b8-11e8-9bba-159a9f717429.png)

![image](https://user-images.githubusercontent.com/1092318/45223791-8af77580-b2b8-11e8-91f7-06e37d01e111.png)

no setter or getter for retailerId

![image](https://user-images.githubusercontent.com/1092318/45223917-ea558580-b2b8-11e8-9c5b-f64918cc22e5.png)

![image](https://user-images.githubusercontent.com/1092318/45223932-fa6d6500-b2b8-11e8-8688-3b349f192959.png)

Any ideas?

**Comment by delyriand** [comment]
I do not want module version in magento but in composer :). Give me result of `composer info smile/module-store-delivery`

**Comment by samc2810** [comment]
thanks for the hint
somehow i had to switch to the developer mode and delete the generated code folder

turning back to production mode generated the setters and getters for retailerId too


Thanks for the cool module :)
