### ISSUE TITLE
Place Order button is greyed out when Store Pickup shipping method is selected

### ISSUE THREAD

**Issue by ozzman6154** [Smile-SA/elasticsuite-for-retailer#23]
It is observed that a user cannot place an order when shipping method selected is Store Pickup.  After selecting "Store Pickup" as the shipping method on Shipping page and then navigating to Payment page, the shipping method is displayed as "undefined". The Store address is correct.

### Preconditions
Magento Commerce Cloud 2.3.0
Smile_StoreLocator 1.2.2
Smile_StoreDelivery 1.2.0

Environment : Production
https://mcprod.bronsonsafety.com.au/

Third party modules : N/A.  Can be reproduced on clean install of Magento EE 2.3.0

### Steps to reproduce
Please refer to video link: https://youtu.be/LdMAt6aBok0

### Expected result
1. Shipping method must be displayed on Payment page as per what was selected on Shipping page
2. User can place order as parameters are correct.

### Actual result
1. Shipping method displayed on Payment page is "undefined".
2. User cannot place order as Order button is greyed out.

**Comment by Fdec** [comment]
Hi @ozzman6154 

It's an old issue, have you fix it on your project ? Can you purpose a PR ?

thanks
