### ISSUE TITLE
IsDiscount::getSearchQuery() has wrong signature

### ISSUE THREAD

**Issue by richard-parnaby-king** [Smile-SA/elasticsuite-for-retailer#29]
Attempting to install this module and get getting a fatal error that the signature for IsDiscount::getSearchQuery does not match the parent signature.

    PHP Fatal error:  Declaration of Smile\RetailerOffer\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount::getSearchQuery() must be compatible with Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount::getSearchQuery(Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product $condition) in /vendor/smile/module-retailer-offer/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php on line 72

### Preconditions
Using Magento 2.4 EE on Cloud. 

### Steps to reproduce

1. composer require smile/elasticsuite-for-retailer
2. git add . -A && git commit -am 'Added elasticsuite' && git pull && git push
3. ^^joined above lines with && for brevity. Naturally I do this as separate commands.

### Expected result

1. Magento cloud runs upgrade and di compilation with no issues.

### Actual result

1. Compilation error due to mismatching signatures.

Here we can see Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount, the signature for the function `getSearchQuery` is: `public function getSearchQuery(ProductCondition $condition)`.
![core](https://user-images.githubusercontent.com/4233826/117302957-182d6680-ae74-11eb-8ac1-81b6ac758cfa.PNG)

Smile\RetailerOffer\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount (that extends from the above) has the following signature: public function getSearchQuery()
![module](https://user-images.githubusercontent.com/4233826/117302958-195e9380-ae74-11eb-8f6a-95084c2a211a.PNG)

**Comment by chrey** [comment]
+1, this is quite a blocking issue as it triggers a fatal error in Magento

**Comment by maximbaibakov** [comment]
This is a temporary patch worked for me


```
--- a/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php
+++ b/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php
@@ -16,6 +16,7 @@
 use Magento\Config\Model\Config\Source\Yesno;
 use Smile\ElasticsuiteCatalogRule\Api\Rule\Condition\Product\SpecialAttributeInterface;
 use Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount as BaseIsDiscount;
+use Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product as ProductCondition;
 use Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory;
 use Smile\ElasticsuiteCore\Search\Request\QueryInterface;
 use Smile\StoreLocator\CustomerData\CurrentStore;
@@ -69,9 +70,9 @@
     /**
      * {@inheritdoc}
      */
-    public function getSearchQuery()
+    public function getSearchQuery(ProductCondition $condition)
     {
-        $query = parent::getSearchQuery();
+        $query = parent::getSearchQuery($condition);

         if ($this->settingsHelper->isDriveMode()) {
             $query = $this->getIsDiscountOffersQuery();
```
