### ISSUE TITLE
Retailer detail - PHP exception

### ISSUE THREAD

**Issue by delyriand** [Smile-SA/elasticsuite-for-retailer#4]
### Preconditions
Magento Version : 2.1.9
Module Version : 1.3.0
Environment : Developer

### Steps to reproduce
1. Create a retailer and copy this url_key.
2. Go to detail page : http://mymagento.local/stores/{url_key}

### Expected result
1. Retailer informations (address, opening hour, ...)

### Actual result
1. PHP Exception: Warning: Invalid argument supplied for foreach() in vendor/smile/module-store-locator/Model/Retailer/ScheduleManagement.php on line 128

**Comment by delyriand** [comment]
Another PHP exception in this page : `Fatal error: Uncaught Error: Call to a member function getName() on null in vendor/smile/module-store-locator/Block/View.php on line 74`

Actually, the retailer detail page is without the navigation bar. I think the problem appears when using varnish with esi blocks.

**Comment by romainruaud** [comment]
I close the issue since PRs were merged.

Thank you for contributing.
