### ISSUE TITLE
[RuntimeException] during installation

### ISSUE THREAD

**Issue by bery** [Smile-SA/elasticsuite-for-retailer#6]
Hi,

when trying to install a new site on Magento 2.1.10, I am getting an exception

```
[RuntimeException]
  Source class "\Smile\Retailer\Ui\Component\Retailer\Form\Field" for "Smile\Retailer\Ui\Component\Retailer\Form\FieldMapper" generation does not exist.
```

When I clear var/generation and run the installation again, all works fine.

Would you have any ideas why this might be happening?

Thanks,

Lukas

**Comment by bery** [comment]
And in deed
```
<virtualType name="Smile\Retailer\Ui\Component\Retailer\Form\Modifier\Eav" type="Smile\Seller\Ui\Component\Seller\Form\Modifier\Eav">
        <arguments>
            <argument name="fieldMapper" xsi:type="object">Smile\Retailer\Ui\Component\Retailer\Form\FieldMapper</argument>
        </arguments>
    </virtualType>
```
the class referenced in the object does not exist

**Comment by romainruaud** [comment]
I'm not sure that I understand properly.

Which class is non existing for you ? `Smile\Seller\Ui\Component\Seller\Form\FieldMapper` is existing, so does `Smile\Seller\Ui\Component\Seller\Form\Modifier\Eav`

**Comment by bery** [comment]
The issue is for 
```Source class "\Smile\Retailer\Ui\Component\Retailer\Form\Field" for "Smile\Retailer\Ui\Component\Retailer\Form\FieldMapper" generation does not exist.```

**Comment by delyriand** [comment]
Hi @bery,

Which version of the module do you use?

Best regard
