### ISSUE TITLE
Global header / footer showing in checkout

### ISSUE THREAD

**Issue by johnhughes1984** [Smile-SA/elasticsuite-for-retailer#9]
## Overview
The wrong header and footer is being displayed in the checkout when using the `Smile_StoreDelivery` module

## Steps to replicate
1. Add any product to the cart.
2. Navigate to the checkout.

## Expected Result
The isolated checkout header and footer content should be displayed at checkout.

## Actual Result
The global header and footer content is displayed at checkout.

## Solution
Remove `layout="1column"` from https://github.com/Smile-SA/magento2-module-store-delivery/blob/master/view/frontend/layout/checkout_index_index.xml so the page layout reverts back to `checkout` (as set in `Magento_Catalog`)

**Comment by johnhughes1984** [comment]
PR created: https://github.com/Smile-SA/magento2-module-store-delivery/pull/8

**Comment by romainruaud** [comment]
PR merged, thank you for contributing.
